server:
  port: 8898
spring:
  application:
    name: coin-common
  datasource:
    password: Ltd2022@$
    username: root
    url: jdbc:mysql://mysql-server:3307/coin_exchange
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis-server
    port: 6380
    password: Ltd2022@$
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8858

swagger2:
  basePackage: com.bjsxt.controller
  name: fengyunkai
  url: https://github.com/fyk943749465
  email: fyk943749465@gmail.com
  title: Coin-common test
  description: Coin-Common moudle test
  version: 1.0
  termsOfServiceUrl: www.xjp.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password:  ${spring.redis.password}